using System.Collections.Generic;

namespace Manor.Narrative
{
    public static class ManorTextCatalog
    {
        private static readonly Dictionary<string, string> Texts = new Dictionary<string, string>
        {
            { "OBJ_FIND_WHERE_I_AM", "弄清楚我在哪里" },
            { "OBJ_TEST_INTERACTIONS", "测试门、钥匙和纸条交互" },
            { "OBJ_FIND_LOCKPICK_WIRE", "寻找能撬开祷告室门锁的细铁丝" },
            { "OBJ_UNLOCK_PRAYER_ROOM", "在祷告室门前按住 K 撬锁" },
            { "OBJ_FIND_RESEARCH_KEY", "在祷告室内寻找研究室钥匙" },
            { "OBJ_INVESTIGATE_RESEARCH_ROOM", "进入 G10 研究室调查记录" },
            { "OBJ_OPEN_KITCHEN_HATCH", "综合线索，返回 G03 后勤区寻找活板门" },
            { "OBJ_DESCEND_TO_BASEMENT", "从 G03 活板门进入 B01 地下服务路线" },
            { "OBJ_INVESTIGATE_RITUAL_ROOM", "沿 B01 深入 B02 地下祭祀室" },
            { "OBJ_COMMUNICATE_WITH_WRAITH", "使用完整羊皮纸回应孕妇怨灵" },
            { "OBJ_SURVIVE_UNTIL_DAWN", "屠夫已经苏醒：不要战斗，利用庄园路线坚持到黎明" },
            { "OBJ_RESTORE_BRIDGE", "黎明已到，操作机关恢复桥梁" },
            { "OBJ_ESCAPE_GATE", "穿过桥梁，在庄园大门输入 1016" },
            { "OBJECTIVE_PREFIX", "当前任务：" },
            { "PROMPT_OPEN_DOOR", "按 E 开门" },
            { "PROMPT_CLOSE_DOOR", "按 E 关门" },
            { "PROMPT_LOCKED_DOOR", "需要钥匙" },
            { "PROMPT_PICKUP_KEY", "按 F 拾取钥匙" },
            { "PROMPT_PICKUP_ITEM", "按 F 拾取物品" },
            { "PROMPT_ENTER_INTERIOR", "按 E 进入主楼" },
            { "PROMPT_RETURN_COURTYARD", "按 E 返回庭院" },
            { "PROMPT_GATE_KEYPAD", "按 E 输入庄园大门密码" },
            { "PROMPT_GATE_PASSWORD_UNKNOWN", "还不知道大门密码" },
            { "PROMPT_GATE_BRIDGE_BLOCKED", "桥梁尚未恢复，无法逃离" },
            { "PROMPT_VAULT_WINDOW", "按 E 翻越窗户" },
            { "PROMPT_READ_NOTE", "按 E 阅读纸条" },
            { "PROMPT_HOLD_K_LOCKPICK", "按住 K 约 5 秒撬锁" },
            { "PROMPT_NEED_LOCKPICK_WIRE", "需要一根细铁丝" },
            { "PROMPT_OPEN_HATCH", "按 E 打开厨房活板门" },
            { "PROMPT_CLOSE_HATCH", "按 E 关闭厨房活板门" },
            { "PROMPT_HATCH_NEEDS_CLUES", "还不能确定这里通往地下" },
            { "PROMPT_USE_PARCHMENT", "按 E 使用完整羊皮纸沟通" },
            { "PROMPT_NEED_PARCHMENT", "需要完整羊皮纸" },
            { "PROMPT_COMMUNICATION_COMPLETE", "沟通已经完成" },
            { "CLUE_ADDED", "已记录新线索" },
            { "KEY_ADDED", "已获得钥匙" },
            { "ITEM_ADDED", "物品已收起" },
            { "WINDOW_VAULTED", "翻过了窗户" },
            { "DOOR_OPENED", "门已打开" },
            { "DOOR_CLOSED", "门已关闭" },
            { "GATE_PASSWORD_CORRECT", "密码正确：大门已解锁" },
            { "GATE_PASSWORD_WRONG", "密码错误，请重试" },
            { "GATE_PASSWORD_UNKNOWN", "先查明大门密码" },
            { "GATE_BRIDGE_BLOCKED", "必须等到黎明并恢复桥梁" },
            { "NEED_LOCKPICK_WIRE", "没有合适的撬锁工具" },
            { "LOCKPICK_SUCCEEDED", "锁舌松开了，现在可按 E 开门" },
            { "WIRE_ADDED", "获得细铁丝，可用于撬锁" },
            { "HATCH_NEEDS_CLUES", "需要先查明拖痕、日记和研究记录之间的联系" },
            { "HATCH_OPENED", "活板门打开了，下面有一条服务楼梯" },
            { "HATCH_CLOSED", "活板门已关闭" },
            { "CLUE_G08_DIARY_TITLE", "床下日记" },
            { "CLUE_G08_DIARY_BODY", "日记属于被困在这里的孕妇。她失去的是自己的家庭；庄园中的两个孩子来自另外两个家庭，与她没有亲子关系。" },
            { "CLUE_G04_TRACES_TITLE", "后勤区拖痕" },
            { "CLUE_G04_TRACES_BODY", "石灰粉、木屑和潮湿拖痕从工作间延伸向厨房后勤区，像是有人长期搬运重物并遮盖地面入口。" },
            { "CLUE_G10_RITUAL_TITLE", "残缺阵图与搬运清单" },
            { "CLUE_G10_RITUAL_BODY", "记录提到四个祭品位置、锁魂钉和厨房下方的服务通路；G06 的旧入口早已封死。" },
            { "CLUE_G09_BOY_TITLE", "男童的木制小车与家庭标记" },
            { "CLUE_G09_BOY_BODY", "磨损的小车刻着一户乡村家庭的记号和男童名字。他与房间另一侧的女孩并非一家人。" },
            { "CLUE_G09_GIRL_TITLE", "女童的纸风车与发带" },
            { "CLUE_G09_GIRL_BODY", "破纸风车、旧裙和发带记录着另一户家庭与女孩名字。她不是男童的双胞胎，也不是孕妇的孩子。" },
            { "NEED_PARCHMENT", "还没有取得完整羊皮纸" },
            { "PROMPT_NEED_VICTIM_CLUES", "还没有理解三名受害者的身份" },
            { "NEED_VICTIM_CLUES", "先确认孕妇与两个来自不同家庭的孩子分别是谁" },
            { "COMMUNICATION_RETRY", "羊皮纸上的字迹散去——这个回答没有触及真相，可以重试" },
            { "COMMUNICATION_SUCCEEDED", "怨气消散。你得知大门密码是 1016，屠夫将在黎明石化" },
            { "PARCHMENT_ADDED", "获得完整羊皮纸" },
            { "DAWN_TRIGGERED", "黎明到来，屠夫开始石化；桥梁机关现在可以操作" },
            { "PROMPT_RESTORE_BRIDGE", "按 E 操作机关恢复桥梁" },
            { "PROMPT_BRIDGE_NOT_DAWN", "机关被锁死，黎明前无法操作" },
            { "PROMPT_BRIDGE_RESTORED", "桥梁已经恢复" },
            { "BRIDGE_NOT_DAWN", "现在操作机关没有反应" },
            { "BRIDGE_RESTORING", "桥梁正在恢复" },
            { "ESCAPE_COMPLETE", "你已逃离庄园" },
            { "WRAITH_GRAPPLE", "怨灵抓住了你：按住 E 约 5 秒挣脱，15 秒内必须成功" },
            { "WRAITH_ESCAPED", "你挣脱了怨灵" },
            { "BUTCHER_WARNING", "远处传来沉重脚步和桥梁断裂声——屠夫苏醒了" },
            { "BUTCHER_PETRIFIED", "屠夫在黎明中停止行动并逐渐石化" },
            { "NOTE_ALREADY_READ", "已读线索" },
            { "TEST_NOTE_TITLE", "测试纸条" },
            { "TEST_NOTE_BODY", "这是一张用于验证基础交互的灰盒纸条。阅读后会加入已读线索列表；它不属于正式剧情。" },
            { "TEST_CONTROLS", "WASD 移动　鼠标转视角　E 交互　F 拾取　K 长按使用　Tab 线索　Esc 暂停/关闭" },
            { "CLUE_PANEL_TITLE", "线索记录" },
            { "CLUE_EMPTY", "尚未阅读测试纸条。" },
            { "CLUE_CLOSE_HINT", "按 Tab 或 Esc 返回" },
            { "PAUSE_TEXT", "游戏已暂停\n按 Esc 返回" },
            { "PAUSED", "游戏已暂停" },
            { "DEATH_TITLE", "汤姆未能逃脱" },
            { "RETRY", "重新开始" }
        };

        public static string Resolve(string key)
        {
            if (string.IsNullOrWhiteSpace(key)) return string.Empty;
            return Texts.TryGetValue(key, out string value) ? value : key;
        }
    }
}
